config/routes.rb
Rails.application.routes.draw do
  resources :projects
  #root to: "homes#new"
  root to: 'places#index'

  get 'comment1s/new'
  get 'comment1s/create'
  get 'comment1s/show'
  get 'post1s/new'
  get 'post1s/create'
  get 'post1s/show'
  get 'appointments/new'
  get 'homes/new'

  get 'physicians/index'
  get 'physicians/show'
  get 'physicians/new'
  get 'physicians/create'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/create'
  get 'patient/index'
  get 'patient/show'
  get 'patient/new'
  get 'patient/create'

  resources :patients 
  resources :physicians 
  resources :appointments
  #resources :comments
  #resources :posts
  
  resources :places, only: [:new, :create, :edit, :update]
  resources :authors, only: [:new, :create, :edit, :update]

	resources :users
	resources :subscriptions

  resources :post1s
  resources :comment1s
  get 'like/create'  => 'likes#create'
  get 'like/show'  => 'likes#show'

  #get '/subscription/new' => 'users#subscription_create'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :place, optional: true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/comment1.rb
class Comment1 < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointments
    has_many :patients, through: :appointments
end

app/models/place.rb
class Place < ApplicationRecord
	#has_many :addresses, dependent: :destroy
	has_many :addresses, dependent: :destroy, inverse_of: :place
	#accepts_nested_attributes_for :addresses
	accepts_nested_attributes_for :addresses, allow_destroy: true,
                              reject_if: ->(attrs) { attrs['city'].blank? || attrs['street'].blank? }
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes, as: :likeable
	#has_many :comments
end

app/models/post1.rb
class Post1 < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user , optional: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :subscription
end

app/models/user1.rb
class User1 < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def  index
    @users = User.all
  end
    @subscription = Subscription.new
  
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(name: params[:user]['name'],email: params[:user]['email'],password: params[:user]['password'])
    @user.save!
    redirect_to @user
  end

  def subscription_create
    @user = User.find(params[:id])
    @user.build_subscription().save
    redirect_to :action => :index
  end

  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

   def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :action => :index
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit user below</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %></br>

  <%= f.label :email %>
  <%= f.text_field :email %></br>

  <%= f.label :password %>
  <%= f.text_field :password %></br>

  <%= f.submit "submit" %>
<% end %>

app/views/users/index.html.erb
<h1>Listing users....</h1>
<table>
  <tr>
    <th>Name:</th>
    <th>Email:</th>
    <th>Password:</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
       <td><%= link_to 'Edit', edit_user_path(user) %></td>
       <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure....?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h2>with form_tag</h2>
<%= form_tag users_path do %>
   <label>Name:</label>
   <%= text_field_tag :'user[name]' %>
</br>
</br>

   <label>E mail:</label>
   <%= text_field_tag :'user[email]' %>
</br>
</br>
   <label>password:</label>
   <%= text_field_tag :'user[password]'%>
 </br>
 </br>
   <%= submit_tag "Create User"%>
<%end%>

app/views/users/show.html.erb
<h2>showing user....</h2>
<%= @user.name%></br>
<%= @user.email%></br>
<%= @user.password%></br>
<%= link_to 'edit', controller: 'users' %>
</br>
<%#= link_to 'Add subscription', subscription_new_path(:id => @user.id)%>
</br>
<%= link_to 'subscription', new_subscription_path(@user.id)%>