config/routes.rb
Rails.application.routes.draw do
  resources :projects
  #root to: "homes#new"
  root to: 'places#index'

  get 'comment1s/new'
  get 'comment1s/create'
  get 'comment1s/show'
  get 'post1s/new'
  get 'post1s/create'
  get 'post1s/show'
  get 'appointments/new'
  get 'homes/new'

  get 'physicians/index'
  get 'physicians/show'
  get 'physicians/new'
  get 'physicians/create'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/create'
  get 'patient/index'
  get 'patient/show'
  get 'patient/new'
  get 'patient/create'

  resources :patients 
  resources :physicians 
  resources :appointments
  #resources :comments
  #resources :posts
  
  resources :places, only: [:new, :create, :edit, :update]
  resources :authors, only: [:new, :create, :edit, :update]

	resources :users
	resources :subscriptions

  resources :post1s
  resources :comment1s
  get 'like/create'  => 'likes#create'
  get 'like/show'  => 'likes#show'

  #get '/subscription/new' => 'users#subscription_create'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :place, optional: true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/comment1.rb
class Comment1 < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointments
    has_many :patients, through: :appointments
end

app/models/place.rb
class Place < ApplicationRecord
	#has_many :addresses, dependent: :destroy
	has_many :addresses, dependent: :destroy, inverse_of: :place
	#accepts_nested_attributes_for :addresses
	accepts_nested_attributes_for :addresses, allow_destroy: true,
                              reject_if: ->(attrs) { attrs['city'].blank? || attrs['street'].blank? }
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes, as: :likeable
	#has_many :comments
end

app/models/post1.rb
class Post1 < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user , optional: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :subscription
end

app/models/user1.rb
class User1 < ApplicationRecord
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def  index
    @subscriptions = Subscription.all
  end

  def new
    @subscription = Subscription.new
  end

  def show
    @subscription = Subscription.find(params[:id])
  end
  def edit
    @subscription = Subscription.find(params[:id])
  end

  def create
    @subscription = Subscription.new(name: params[:subscription]['name'],plan_id: params[:subscription]['plan_id'], user_id: params[:subscription]["id"])
    @subscription.save!
    redirect_to @subscription
  end

  def update
    @subscription = Subscription.find(params[:id])
 
    if @subscription.update(subscription_params)
      redirect_to @subscription
    else
      render 'edit'
    end
  end

   def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
 
   redirect_to :action => :index
  end
  
  private
    def subscription_params
      params.require(:subscription).permit(:name, :plain_id)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subscriptions/edit.html.erb
<h1>Edit subscription  below</h1>
<%= form_for @subscription do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %></br>

  <%= f.label :plan_id %>
  <%= f.text_field :plan_id %></br>

  <%= f.submit "submit" %>
<% end %>

app/views/subscriptions/index.html.erb
<h1>Listing subscription....</h1>
<table>
  <tr>
    <th>Name:</th>
    <th>plan_id:</th>
    <th colspan="3"></th>
  </tr>
 
  <% @subscriptions.each do |subscription| %>
    <tr>
      <td><%= subscription.name %></td>
      <td><%= subscription.plan_id %></td>
      <td><%= link_to 'Show', subscription_path(subscription) %></td>
       <td><%= link_to 'Edit', edit_subscription_path(subscription)%></td>
       <td><%= link_to 'Destroy', subscription_path(subscription),
              method: :delete,
              data: { confirm: 'Are you sure....?' } %></td>
    </tr>
  <% end %>
</table>

app/views/subscriptions/new.html.erb
<h2>with form_for </h2>
<%= form_for @subscription do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
</br>
</br>
  <%= f.label :plan_id %>
  <%= f.text_field :plan_id %>
</br>
</br>
  <%=f.hidden_field :id, :value => params["format"] %>
</br>
  <%=f.submit "Create" %>
<% end %>


<h2>with form_tag</h2>
<%= form_tag subscriptions_path do %>
   <label>Name:</label>
   <%= text_field_tag :'user[name]' %>
</br>
</br>

   <label>Plan_id:</label>
   <%= text_field_tag :'user[plan_id]' %>
</br>  
   <%= submit_tag "Create User" %>
<%end%>

app/views/subscriptions/show.html.erb
<%= @subscription.name%></br>
<%= @subscription.plan_id%></br>
<%= link_to 'edit', controller: 'subscriptions' %>