config/routes.rb
Rails.application.routes.draw do
  resources :projects
  #root to: "homes#new"
  root to: 'places#index'

  get 'comment1s/new'
  get 'comment1s/create'
  get 'comment1s/show'
  get 'post1s/new'
  get 'post1s/create'
  get 'post1s/show'
  get 'appointments/new'
  get 'homes/new'

  get 'physicians/index'
  get 'physicians/show'
  get 'physicians/new'
  get 'physicians/create'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/create'
  get 'patient/index'
  get 'patient/show'
  get 'patient/new'
  get 'patient/create'

  resources :patients 
  resources :physicians 
  resources :appointments
  #resources :comments
  #resources :posts
  
  resources :places, only: [:new, :create, :edit, :update]
  resources :authors, only: [:new, :create, :edit, :update]

	resources :users
	resources :subscriptions

  resources :post1s
  resources :comment1s
  get 'like/create'  => 'likes#create'
  get 'like/show'  => 'likes#show'

  #get '/subscription/new' => 'users#subscription_create'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :place, optional: true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :physician
    belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/comment1.rb
class Comment1 < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
	has_many :appointments
    has_many :patients, through: :appointments
end

app/models/place.rb
class Place < ApplicationRecord
	#has_many :addresses, dependent: :destroy
	has_many :addresses, dependent: :destroy, inverse_of: :place
	#accepts_nested_attributes_for :addresses
	accepts_nested_attributes_for :addresses, allow_destroy: true,
                              reject_if: ->(attrs) { attrs['city'].blank? || attrs['street'].blank? }
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes, as: :likeable
	#has_many :comments
end

app/models/post1.rb
class Post1 < ApplicationRecord
	has_many :likes, as: :likeable
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user , optional: true
end

app/models/user.rb
class User < ApplicationRecord
	has_one :subscription
end

app/models/user1.rb
class User1 < ApplicationRecord
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
    2.times {@place.addresses.build}
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @place = Place.find_by(id: params[:id])
  end

  def update
     @place = Place.find_by(id: params[:id])
  if @place.update_attributes(place_params)
    redirect_to root_path
  else
    render :edit
    end
  end

  private
  def place_params
    params.require(:place).permit(:title, addresses_attributes: [:id, :city, :street, :_destroy])
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/places/_address_fields.html.erb
<div class="nested-fields">
  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.check_box :_destroy %>

  <%= link_to_remove_association "remove address", f %>
</div>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <%= render 'shared/errors', object: @place %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <p><strong>Addresses:</strong></p>

    <div id="addresses">
      <%= f.fields_for :addresses do |address| %>
        <%= render 'address_fields', f: address %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add address', f, :addresses%>
      </div>
    </div>
  </div>

  <%= f.submit %>
<% end %>

app/views/places/_place.html.erb
<li>
    <strong><%= place.title %></strong> | <%#= link_to 'Edit place', edit_place_path(place) %><br>
  <% if place.addresses.any? %>
    Addresses:
    <ul>
      <% place.addresses.each do |addr| %>
        <li>
          <%= addr.city %>, <%= addr.street %>
        </li>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/places/index.html.erb
<h1>Places</h1>

<p><%= link_to 'Add place', new_place_path %></p>

<ul><%= render @places %></ul>


<p><%#= link_to 'Add Author', new_author_path %></p>

<ul><%#= render @authors %></ul>

app/views/places/new.html.erb
<h1>Add place</h1>

<%= render 'form' %>